// Code generated by tygo. DO NOT EDIT.

//////////
// source: article.go

export interface Article {
  title: string;
  description: string;
  content: string;
  link: string;
  site_link: string;
  updated_at: string;
  published_at: string;
  guid: string;
  authors: (Person | undefined)[];
  image?: Image;
  categories: (Category | undefined)[];
}

//////////
// source: category.go

export interface Category {
  term: string;
}

//////////
// source: collection.go

export interface Collection {
  user: string;
  title: string;
}

//////////
// source: image.go

export interface Image {
  url: string;
  title: string;
}

//////////
// source: newsfeed.go

export interface Newsfeed {
  title: string;
  description: string;
  feed_link: string;
  site_link: string;
  updated_at: string;
  published_at: string;
  authors: (Person | undefined)[];
  language: string;
  copyright: string;
  image?: Image;
  categories: (Category | undefined)[];
  feed_type: string;
  articles: (Article | undefined)[];
}

//////////
// source: person.go

export interface Person {
  name: string;
  email: string;
}

//////////
// source: subscribe_request.go

export interface SubscribeRequest {
  user_id: string;
  title: string;
  description: string;
  feed_link: string;
  site_link: string;
  updated_at: string;
  published_at: string;
  authors: (Person | undefined)[];
  language: string;
  copyright: string;
  image?: Image;
  categories: string[];
  feed_type: string;
  articles: (Article | undefined)[];
}

//////////
// source: subscription.go

export interface Subscription {
  user_id: string;
  feed_id: string;
}
export interface SubscriptionDTO {
  id: string;
  user_id: string;
  feed_id: string;
}
